app:
  name: notification-service
  env: local
  port: 8098
  log_level: 0 # Debug level

mysql:
  host: localhost
  port: 3306
  database: notification
  username: notif_app
  password: Notif@1234!
  params: "parseTime=true&charset=utf8mb4&loc=UTC"

redis:
  addr: "localhost:6379"
  password: "Redis@123"
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topic: "notifications"

prometheus:
  enabled: true
