app:
  name: notification-service
  env: local
  port: 8098
  log_level: 0 # Debug level

mysql:
  host: notif-mysql
  port: 3306
  database: notification
  username: notif_app
  password: Notif@1234!
  params: "multiStatements=true&parseTime=true&charset=utf8mb4&loc=UTC"

  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 60 # seconds

redis:
  addr: "notif-redis:6379"
  password: "Redis@123"
  db: 0

kafka:
  brokers:
    - "notif-kafka:9092"
  topic: "notifications"

prometheus:
  enabled: true

smtp:
  host: notif-mailhog
  port: 1025
  username: ""
  pass: ""
  from: "no-reply@notify.local"

slack:
  webhook_url: ""